### ISSUE TITLE
Linked Posts

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#10]
**Is your feature request related to a problem? Please describe.**
As a comment writer I want to be able to direct a post author to another story or discussion if I think that they will be able to find already available, additional information there.

**Describe the solution you'd like**
Add a button to enter a post URL and display it as a small note directly below the post

**Additional context**
There's one important catch here: WE DO NOT WANT THE BAD BEHAVIOR FROM STACKOVERFLOW on Hashnode. So any descriptive texts should be written in a way that make it clear that we want to help someone by pointing them to _additional_ resources on Hashnode, not close and lock as many questions as possible.

**Comment by BolajiAyodeji** [comment]
Hi, @minecrawler ,
Comments can be written in markdown and you can easily point someone to another post like so:
![image](https://user-images.githubusercontent.com/30334776/61946686-265e0b80-af9b-11e9-9ca8-980b065591fe.png)

**Comment by BolajiAyodeji** [comment]
I'll be closing this, for now, thank you for reporting this.

**Comment by minecrawler** [comment]
@BolajiAyodeji yes, however we cannot reply to a post directly (only to comments), and most of the time, if I just want to tell someone that their question was already answered, I do not want to notify several thousand followers of mine at the same time. The current way, hence, is not sufficient.
