### ISSUE TITLE
Image cropped on Chrome mobile view

### ISSUE THREAD

**Issue by thamaraiselvam** [Hashnode/user-feedback#101]
**Describe the bug**
Header image got cropped on mobile view

**To Reproduce**
1. Go to this link - https://thamaraiselvam.com/create-extensions-for-vs-code-part-1-cjx5r238f000t65s1ag0fdn8e
2. Check both on desktop and mobile

**Screenshots**
![64530799_2688037828091213_3104012335568650240_n](https://user-images.githubusercontent.com/6559664/59905525-1b580e80-9424-11e9-9ee8-6820d2afa2cd.jpg)

**Smartphone:**
 - Device: OnePlus 6T
 - OS: Android 9
 - Browser: Google Chrome
 - Version: 75.0.3770.101

**Comment by BolajiAyodeji** [comment]
Hi @thamaraiselvam, thanks for reporting.

This issue is fixed now, please check again.
