### ISSUE TITLE
Codesandbox embed is not working well

### ISSUE THREAD

**Issue by atapas** [Hashnode/user-feedback#103]
**Describe the bug**
I am trying to embed the CodeSandbox into my blog but it is not working out well.

- I have tried this 
  %[https://codesandbox.io/s/test-rdoyi]
- Also tried this
 <iframe src="https://codesandbox.io/s/test-rdoyi?codemirror=1" style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;" sandbox="allow-modals allow-forms allow-popups allow-scripts allow-same-origin"></iframe>

The last one embeds but with some ugly anchors

**To Reproduce**
Create a draft and add the embeds as explained above

**Expected behavior**
Embed to work correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/3633137/61209430-5abe0600-a717-11e9-943d-0b121bb0bfa1.png)

![image](https://user-images.githubusercontent.com/3633137/61209480-83460000-a717-11e9-8198-547928d7d48b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @atapas, thanks for reporting.

Please check again as this is fixed now.
