### ISSUE TITLE
Launch Daily Digest beside Hashnode Weekly

### ISSUE THREAD

**Issue by 41x3n** [Hashnode/user-feedback#104]
**Is your feature request related to a problem? Please describe.**
What pushed me towards Medium at the beginning was that they used to send a digest email every day which ultimately made me check that site every morning that later turned into a habit. Same does not happen for Hashnode because I get email only once a week.

**Describe the solution you'd like**
Nothing much. Just push a daily digest with top articles so that users can read more Hashnode articles and interact with them.

**Comment by scriptonist** [comment]
Hey, @41x3n thanks for letting us know, we were also thinking about the same for a bit now. You can expect this feature very soon 🚀
