### ISSUE TITLE
Add support for "suggesting" social media sharing

### ISSUE THREAD

**Issue by marianopeck** [Hashnode/user-feedback#105]
**Is your feature request related to a problem? Please describe.**
Not a problem but something that could be improved. 

**Describe the solution you'd like**
For example, in other platforms you can tell them a suggested "tweet text".. which, depending on a various factors I imagine they tweet it or not. Sometimes they manually type the content of the tweet based on what a human read on your post and thought it was interesting. Sometimes they just take exactly what you suggested. I see for example in above tweet, someone wrote that:  

> Want to get started with Docker and Smalltalk?
> @MartinezPeck
>  got you covered!
> Check out his article - Getting started with Docker and Smalltalk by clicking the link below 👇

Again, thanks for that. But I wonder, wouldn't it be a good idea for you to also allow the blogger to "suggest you" that? It would also save you time. I could image a text input on the bottom of a blog post (see attached screenshot example) together with the canonical url, tags, cover, etc. 

**Describe alternatives you've considered**
Talking with Lazar Pavlovic he suggest he could send me a PM for suggesting in case any of my posts would be selected for social media.

**Additional context**
For further details check private email with Milica Maksimovic

**Comment by fazlerocks** [comment]
Great feedback. We'll pass this to the team. 👍

**Comment by BolajiAyodeji** [comment]
Hi @marianopeck, this is implemented already. Thanks for the feedback!
