### ISSUE TITLE
sitemap.xml is empty

### ISSUE THREAD

**Issue by marianopeck** [Hashnode/user-feedback#106]
**Describe the bug**
 I still not able to submit the sitemap.xml because its still empty. Do you have examples of sitemap.xml files? how can I submit mine?
I see how to tell google to submit my sitemap.xml but mine looks empty: https://martinezpeck.hashnode.dev/sitemap.xml

**To Reproduce**
1. Go to https://martinezpeck.hashnode.dev/sitemap.xml
2. Its empty...

**Expected behavior**
I expect something not empty, like when I enter my [canonical blog](https://marianopeck.wordpress.com/sitemap.xml)

**Additional context**
Original bug report started in private email with Milica Maksimovic and she says the problem is only with my blog :(

**Comment by sandeeppanda92** [comment]
Hi Marian! This looks like a bug -- I am looking into it.

**Comment by sandeeppanda92** [comment]
Just submitted a fix. :-) It had something to do with usernames having both uppercase characters. Thanks for noticing and reporting. 🙌

**Comment by marianopeck** [comment]
Excellent! Thanks a lot for the quick fix. I can report it works nicely now :)
