### ISSUE TITLE
[Android App] Google Sign In not working

### ISSUE THREAD

**Issue by antarikshc** [Hashnode/user-feedback#107]
**Describe the bug**
Google Sign-In not working for Devblog login.

**To Reproduce**
1. Go to More > Devblog
2. Click on Google Sign-In
3. See error

**Screenshots**
[Error](https://drive.google.com/open?id=1Uoso7RYPGf74Esn3KKyshiccuP_ZBcYn)

**Smartphone (please complete the following information):**
 - Device: Huawei
 - OS: Android Pie

**Comment by mittalyashu** [comment]
Wait, what?

We can sign in from Android hashnode app. Wasn't knowing that.

**Comment by fazlerocks** [comment]
@antarikshc Devblog and some other sections, like AMAs, open inside Android's Native Webview. They aren't part of the app. The app doesn't support user sign up or login. 

Whatever you see inside the webview is the mobile site. Google's sign-in might have some trouble with webview useragent.
