### ISSUE TITLE
[Android App] Cover Images getting cropped on Feed

### ISSUE THREAD

**Issue by antarikshc** [Hashnode/user-feedback#108]
**Describe the bug**
Cover images on Home feed not fully visible.

**Expected behavior**
Change aspect ratio for ImageView

**Screenshots**
[Feed](https://drive.google.com/open?id=1ssiorHNxdCu0_ZA-zmxR7eBSsW2pliyF)

**Comment by fazlerocks** [comment]
Thanks for reporting this, we'll fix the image ratio in the upcoming release.
