### ISSUE TITLE
[Android] Gray overlay on card while tapping

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#109]
**Describe the bug**

https://youtu.be/6JobshBUF74

**Comment by fazlerocks** [comment]
The whole card is clickable and the gray overlay is the focus related style. We'll fix this experience in the upcoming releases.

**Comment by mittalyashu** [comment]
Instead of adding a gray color overlay, maybe you can add box shadow on focus.

**Comment by BolajiAyodeji** [comment]
Hi @mittalyashu, thanks for reporting.

This issue is fixed already, please check again.
