### ISSUE TITLE
[Android] Consistent icon across interface

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#110]
![Screenshot_20190730-163906](https://user-images.githubusercontent.com/29014463/62124831-deb3e880-b2e8-11e9-9d4d-8a0b01182cce.png)

**Comment by fazlerocks** [comment]
Thanks for the feedback. We are working on a new set of icons for mobile and desktop both.

**Comment by mittalyashu** [comment]
One thing more, as we switch from one page to another.

For example, Stories -> More

Why does it show the name of the page along with Logo? That's weird.
