### ISSUE TITLE
Not able to login to the App

### ISSUE THREAD

**Issue by ssmalan94** [Hashnode/user-feedback#111]
Steps 
1. Go to the  Users menu in Android app and click Sign-in
2 Enter the mail id and click Sign in
3 navigate to Gmail and click secure signin button in hashnode email
 4 it will login only on chrome not in app
Expected
After cliking the secure login it should redirect to the app and allow the user to login

**Comment by theevilhead** [comment]
Hey @ssmalan94, 
Thank you for your time. Currently, login/sign up is not supported in the mobile app. All the links/buttons in MoreScreen open in a webview. So, you will be logged in there.
I will be closing this issue. Let us know if you have any suggestions/queries/bug reports.

**Comment by ssmalan94** [comment]
@theevilhead  Sure... Thx  for the quick response
