### ISSUE TITLE
android version home page doesn't load

### ISSUE THREAD

**Issue by mohmed98** [Hashnode/user-feedback#113]
**Describe the bug**
when opening the app the home page just loading and don't show any data

**To Reproduce**
check the api calling

**Expected behavior**
should take 2 seconds at most

**Comment by BolajiAyodeji** [comment]
Hi @mohmed98, thanks for reporting this.

Please check again as this is fixed now.

**Comment by mohmed98** [comment]
yeah that's it's much better now. there is small issues in the app GUI though

**Comment by BolajiAyodeji** [comment]
The app is still in Alpha and we're working on fixes and upgrades. Please keep sending your feedbacks.
