### ISSUE TITLE
Delete blog option?

### ISSUE THREAD

**Issue by Jos512** [Hashnode/user-feedback#114]
**Name of the feature**
I clicked on the 'Hashnode devblog' link because I was curious. That immediately made a blog for me. After some looking around I realise that it's not for me, I like the general Hashnode more to post in.

Now I want to remove/disable/hide my blog. How to do so?

**Describe the solution you'd like**
On option that allows me to remove/disable/hide my blog from the public internet.

**Describe alternatives you've considered**
The only alternative solution seems to be to remove all my post?

**Comment by BolajiAyodeji** [comment]
Hi @Jos512, thanks for this feedback.

You can request for deletion of your Devblog. Head to your [settings](https://hashnode.com/settings) and click on the [Publications](https://hashnode.com/settings/publications) tab and request to delete your desired Devblog like so:


![image](https://user-images.githubusercontent.com/30334776/72435431-56de6f80-379e-11ea-8b43-5987d6f933b2.png)

**Comment by developerphilo** [comment]
How can I delete just a blog post incase of multiple post
