### ISSUE TITLE
Autohide keypad

### ISSUE THREAD

**Issue by tetra49logz** [Hashnode/user-feedback#115]
Whenever I try to write/ask the text area is hidden as the keypad pops up. The same while message option also. please keep the text area to be always visible if the keypad pops up

**Comment by BolajiAyodeji** [comment]
Hi @tetra49logz, thanks for this feedback.

Kindly make use of the **Issue: Feature Enhancement** template to help us better understand your feedback. I'll be closing this issue, for now, feel free to reopen once this is updated.

**Comment by BolajiAyodeji** [comment]
Hi @tetra49logz, any update on this?
