### ISSUE TITLE
Enable sharing articles or blogs in android app

### ISSUE THREAD

**Issue by subodh-dharma** [Hashnode/user-feedback#116]
**Name of the feature**
Sharing Blog or Articles from Android app

**Describe the solution you'd like**
Currently, there is no way I can share an article or a blog page to anyone. I cannot access the *Share* option nor can I get the link to the article to copy and paste the link to any communication app. It would be great to have option in the android app for the same.

**Describe alternatives you've considered**
Need to search on the browser on hashnode website, navigate to the article and copy the link.

**Comment by BolajiAyodeji** [comment]
Hi @subodh-dharma, thanks for this feedback.

Please note that the Android app is a work in progress and this feature will be added soon.
Please exercise some patience and you will be updated once it's live.
