### ISSUE TITLE
Create a form-based feature/bug/enhancement form in apps and website

### ISSUE THREAD

**Issue by subodh-dharma** [Hashnode/user-feedback#117]
**Is your feature request related to a problem? Please describe.**
Allow form-based request/bug/feature/enhancement submission which will translate to a GitHub issue just like this.

**Describe the solution you'd like**
Instead of redirecting the user for feedback Github page (this repo), it would be great to use a form-based approach to get all the details. These details will then be converted to a Github Issue with a similar template like this one, thus having a single point of reference to both the reporter and the project maintainers.

The users can stay back and forth using either this Github issue created or respond through the form-based features.

**Describe alternatives you've considered**

**Additional context**
Enabling the above feature will help in getting more feedbacks and won't bother the user to login to Github and open an issue by typing a lengthy formatted problem or request.

**Comment by fazlerocks** [comment]
Hi @subodh-dharma,

Thanks for the feedback. However, we had considered this option and decided to stick with Github right now. :)
