### ISSUE TITLE
UI Bug : HashNode ChangeLog Link is cropped 

### ISSUE THREAD

**Issue by devojoyti** [Hashnode/user-feedback#118]
**Describe the bug**
See the screenshot. 

**To Reproduce**
1. User Login to Hashnode. 
2. Click on the branch sign right of the "switch to dark/light theme" on right part of Hashnode toolbar. 
3. See the Changelog card cropped. 

**Expected behavior**
Should be visible clearly

**Screenshots**
Attached, please see. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Edition 
 - Browser: Google Chrome
![bug](https://user-images.githubusercontent.com/19840930/65120999-2236f300-da0c-11e9-80e3-644a9d2b5560.png)

**Comment by fazlerocks** [comment]
Not applicable to the new design
