### ISSUE TITLE
Who to follow style

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#120]
**Describe the bug**

- vertical scrollbar should not be there

![image](https://user-images.githubusercontent.com/1130708/65168313-82e22200-da44-11e9-851e-fe2c378acb00.png)

Personally, I'd love to see a carousel here instead of the ugly native scrollbar, but that's not a bug per-se...

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 69

**Additional context**

I wonder why you don't do lessons learned and actually do tests before publishing new styles. This is the 3rd or 4th time you change the design and everything is bugged. I am so sad about the QA at LinearBytes...

**Comment by fazlerocks** [comment]
We have hidden the vertical scroll bar. However, the horizontal scroll bar will appear on FF. Firefox doesn't support scrollbar styling with CSS. We won't override the default scrollbar using heavy JavaScript operations.
