### ISSUE TITLE
profile menu style

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#122]
**Describe the bug**

- on narrow browser, the menu container is missing margin to the left

![image](https://user-images.githubusercontent.com/1130708/65168758-7611fe00-da45-11e9-880f-de634eaf0edd.png)

**To Reproduce**
1. Go to profile with a narrow browser

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 69

**Additional context**

I wonder why you don't do lessons learned and actually do tests before publishing new styles. This is the 3rd or 4th time you change the design and everything is bugged. I am so sad about the QA at LinearBytes...

**Comment by fazlerocks** [comment]
Not applicable to the new profile design.

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This issue is fixed, please check again.
