### ISSUE TITLE
DevBlog menu style

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#123]
**Describe the bug**

- scrollbars should not be there

![image](https://user-images.githubusercontent.com/1130708/65169218-6646e980-da46-11e9-976b-d483b62bf7df.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 69

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, this is fixed already. Apologies for the delayed response and thanks for your patience.
