### ISSUE TITLE
Auto-notifications not working

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#124]
**Describe the bug**

I have to refresh the site to see notifications

**Expected behavior**

I get notifications without refreshing the site

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 69

**Comment by sandeeppanda92** [comment]
Just fixed it. Thanks for the report Marco!
