### ISSUE TITLE
improve feed algorithm or bring back recent

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#125]
**Name of the feature**
Ex: Profile page, blogs page, Hashnode editor, etc.

feed algorithm

**Describe the solution you'd like**

Shows me new posts or stuff I haven't seen, yet

**Describe alternatives you've considered**

Bring back recent!

**Additional context**

The feed shows me years old threads I made myself or I answered back then. Only very little fresh content and very invisible between all the overly old stuff. I don't want to read my old stuff. I want back the fresh topics 😐

Also, I used recent in order to get fresh content to colleagues who don't use Hashnode, but since the update, Hashnode is not a viable source as it is any more, so I use other platforms and link them instead.

**Comment by fazlerocks** [comment]
Thanks for the feedback, @minecrawler. 

We are experimenting with a new feed algorithm that shows content based on your interest and what other people similar to you on Hashnode are liking. We will add the "Recent" tab shortly.

**Comment by fazlerocks** [comment]
Hi @minecrawler, you can now sort the feed. Please refer to the following changelog:
https://changelog.hashnode.com/introducing-the-all-new-feed-algorithm-119662
