### ISSUE TITLE
FOUC on load

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#126]
**Describe the bug**

On reloading the page, there is a Flash Of Unstyled Content. I mainly see the Hashnode icon in viewport-filling size.

**Expected behavior**

Only show styled page, or show loading animation until everything is loaded

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 70

**Comment by sandeeppanda92** [comment]
Hi Marco! Do you see this behavior in all the pages or only on a specific URL? Could you add a small recording, if possible?

**Comment by minecrawler** [comment]
I mainly see it on the feed page. I will upload a video when I'm home tonight (in ca. 8h)

**Comment by BolajiAyodeji** [comment]
> I mainly see it on the feed page. I will upload a video when I'm home tonight (in ca. 8h)

Hi @minecrawler, any update on this?

**Comment by minecrawler** [comment]
Ah, the bug is still there, I only forgot about the video. I just wrote a task-item for me so I don't forget again, sorry!

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, any update on this? Are you still experiencing this?

**Comment by minecrawler** [comment]
No, I don't experience it anymore, thank you!
