### ISSUE TITLE
Style: lower side menu has very bad contrast in dark mode

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#127]
**Describe the bug**

The lower side menu in dark mode has black text color.  Items like "What's New" etc. are unreadable.

**Expected behavior**

All text uses default font color (white or light grey for dark mode)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 70

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

The lower side menu in dark mode has a text color of light gray for me. Are you still experiencing this issue and/or how can I reproduce this error?

![image](https://user-images.githubusercontent.com/30334776/72434893-0adefb00-379d-11ea-9921-2c9f128b54a6.png)

**Comment by minecrawler** [comment]
fixed for me, great, thank you!
