### ISSUE TITLE
What's New notification count is broken

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#128]
**Describe the bug**

The counter always shows news (2) even though I read them multiple times already

**Expected behavior**

Counter is reset and hidden or read

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 70

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

Are you still experiencing this?

**Comment by minecrawler** [comment]
I just re-read the news, and now the counter is reset correctly. Thank you for fixing this 👍
