### ISSUE TITLE
Mobile performance 

### ISSUE THREAD

**Issue by pavelloz** [Hashnode/user-feedback#131]
Could use some love :)

Your assets pipeline is not public so i cant make concrete recommendations, but usually lazyloading + smart code splitting are the pieces that can make a night/day difference.  

Also regarding, 3rd party scripts, especially facebook - are opt-in for the authors? Its a well known fact that they can ruin otherwise perfectly fine website, not to mention privacy concerns.

**Comment by BolajiAyodeji** [comment]
Hi @pavelloz, thanks for this feedback.

Kindly make use of the **Issue: Feature Enhancement** template to help us better understand your feedback. I'll be closing this issue, for now, feel free to reopen once this is updated.
