### ISSUE TITLE
Not able to add post from my devblog to an existing series

### ISSUE THREAD

**Issue by atapas** [Hashnode/user-feedback#132]
**Describe the bug**
This is a bug. I have created a post on my devblog say, https://blog.greenroots.info/developers-and-testers-do-you-see-the-end-goal-together-cjzclnwnn001bc4s102jmk17b. Now I am trying to do Add to series.. I get a popup:

![image](https://user-images.githubusercontent.com/3633137/66714326-1a802980-edd3-11e9-8110-cacfc22e3219.png)

I do not see any ways to select my existing series. However I am able to create a series on the go and add the post to that. But it is fine for first time. From next time on, I am not able to add post to existing series.

Another problem is, This popup never closes on escap and hard to find a way to close it than whole page refresh

**To Reproduce**
1. Go to Dev Blog
2. Click options to add to series
3. A popup opens
4. But none of the existing series are listed to select.

**Expected behavior**
All my series to list to select from

**Screenshots**
![image](https://user-images.githubusercontent.com/3633137/66714354-734fc200-edd3-11e9-9c1f-bf9e79b5d766.png)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Note.. if I go to the Hashnode feed and try to open a post and add to series it works from hashnode.com. But strange from my devblog https://blog.greenroots.info/

This needs to be fixed sooner as I am blocked on adding my posts to series I have created.

**Comment by sandeeppanda92** [comment]
Hi Tapas, 

This has been fixed -- however, there is a change in workflow. You can now add posts to series from the post creation page itself. If you edit a post or create a new one, you will see a new dropdown menu at the bottom of the page -- from there you can choose a series.

e.g. 
<img width="490" alt="Screenshot 2019-10-16 at 6 21 28 PM" src="https://user-images.githubusercontent.com/6363251/66921180-4b19ca80-f042-11e9-95e0-bad75ee7008b.png">
