### ISSUE TITLE
As a user, I want tags on the feed back!

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#135]
**Name of the feature**
Ex: Profile page, blogs page, Hashnode editor, etc.

Tags on posts

**Describe the solution you'd like**

There was a time, when a post's tags were displayed on the feed, so I could quickly see which ones were interesting for which topic. Now that the tags are gone, and maybe also due to the fact that I meddle with many technologies, I have lost overview.
Sure, I can read the headline. However that takes time and requires me to think, which takes even more time. No quick skimming for web-dev topics (which are tagged with a selection of tags). Also, there is no way to filter my feed the way I'd like to. I'd love to get back the tags in one way or another.

**Describe alternatives you've considered**

Implement a way to have custom feeds (for example let users define a filter). That would be pretty cool, however quite a bit of work I guess.

**Additional context**

Writing my company-internal digests takes long, and Hashnode doesn't make it easier to distribute interesting links to my co-workers like that.

**Comment by fazlerocks** [comment]
Hey @minecrawler, thanks for raising this issue. We are working on showing tags on the feed. We'll push it as soon as it's ready. 

I didn't quite get the last two lines: 
> Writing my company-internal digests takes long, and Hashnode doesn't make it easier to distribute interesting links to my co-workers like that.

Could you please elaborate?

**Comment by minecrawler** [comment]
Hi @fazlerocks, thank you for your quick reply! The last two lines are just extra context why I personally need this feature 😉

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thank you for reporting.

We have released an update to Hashnode’s feed algorithm to better help you identify posts that are related to you. You will now see tags attached to posts you see on your feeds.

First, you need to personalize your Hashnode experience by following technologies and topics you are interested in.

- Head to https://hashnode.com/tags and follow tags you are interested in
- Now posts shown on your feed will come from posts tagged with tags you already follow

**Comment by minecrawler** [comment]
Thank you for adding back the tags. I think I am in pretty good shape concerning following tags :D
