### ISSUE TITLE
Embed source code being displayed on preview for blog post

### ISSUE THREAD

**Issue by RawPlutonium** [Hashnode/user-feedback#136]
**Describe the bug**
An incomplete xml tag is displayed when embedding is done on a blog post 

**To Reproduce**
1. Go to  write blog
2. Click on embed and paste iframe
3. click on preview

**Expected behavior**
An embedded item would show up without any xml code

**Screenshots**
![Screenshot from 2019-10-29 00-49-04](https://user-images.githubusercontent.com/22885308/67747973-f3fcf800-fa3a-11e9-9308-d937aa1516e2.png)
![Screenshot from 2019-10-28 23-52-16](https://user-images.githubusercontent.com/22885308/67747974-f3fcf800-fa3a-11e9-8671-c4c2d2536015.png)
![Screenshot from 2019-10-28 23-52-11](https://user-images.githubusercontent.com/22885308/67747976-f3fcf800-fa3a-11e9-9faf-e0f48561f48b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 77

**Comment by BolajiAyodeji** [comment]
Hi @RawPlutonium, thanks for reporting this.
I'll relate this to my team and get back to you with an update.

**Comment by BolajiAyodeji** [comment]
Hi @RawPlutonium, this issue is fixed now.
Thanks for your patience :).
