### ISSUE TITLE
I replied to a comment, then my first comment in the thread wasn't there (refresh solved)

### ISSUE THREAD

**Issue by EmilMoe** [Hashnode/user-feedback#138]
**Describe the bug**

I replied to a comment, then my first comment in the thread wasn't there (refresh solved)

**To Reproduce**

**Expected behavior**

My previous comment to be visible

**Screenshots**

![image](https://user-images.githubusercontent.com/555083/67866706-a4492a00-fb29-11e9-8e8a-80702a70c7dc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Latest

https://hashnode.com/post/how-can-i-become-more-involved-with-hashnode-ck2cyv0ag00ojp4s1yqud1rao#ck2czpqvm00p9p4s1a80w9j4e

**Comment by BolajiAyodeji** [comment]
Hi @EmilMoe, thanks for reporting this.

Are you still experiencing this?
There is a `Show all replies` button that opens all comments under the thread now.

![image](https://user-images.githubusercontent.com/30334776/72429298-e7fa1a00-378f-11ea-898b-a20aef9ee177.png)
