### ISSUE TITLE
Inline highlighting for code blocks

### ISSUE THREAD

**Issue by ebenezerdon** [Hashnode/user-feedback#139]
**Name of the feature**
Hashnode Editor

**Describe the solution you'd like**
Currently, I'm not able to publish tutorial articles because there's no way to highlight new blocks that I add to a file. If there was a way to add support for the `<pre>`, `<code>` and `<b>` tags in the markdown editor, that will be really awesome.

**Additional context**
![Screenshot from 2019-11-06 19-11-38](https://user-images.githubusercontent.com/43746609/68325281-5acc8200-00c9-11ea-850d-2c6a458094fb.png)

**Comment by BolajiAyodeji** [comment]
Hi @ebenezerdon,

The editor is a markdown editor, so you have to write your contents in markdown.
There is support for highlighting code and new blocks already.
Please see the **HELP** section of the editor for additional help.

![image](https://user-images.githubusercontent.com/30334776/72428852-d5331580-378e-11ea-92ce-f289ca88b3f7.png)
