### ISSUE TITLE
Image cropped

### ISSUE THREAD

**Issue by daveismyname** [Hashnode/user-feedback#14]
**Describe the bug**
when uploading an image the description says  "Upload at least 800 x 420"

**To Reproduce**
Upload image for a post

**Expected behavior**
Expected to see an image matching the proportions specified, 

**Screenshots**
Uploaded an image that's 800px wide
![](https://i.imgur.com/03fPB3V.png)

Going to the image directly:
![](https://hashnode.imgix.net/res/hashnode/image/upload/v1552732285822/etaViYh4u.png)

so far all good.

But on the blog its cropped:
![](https://hashnode.imgix.net/res/hashnode/image/upload/v1552732285822/etaViYh4u.png?w=1600&h=840&fit=crop&crop=entropy&auto=format,enhance&q=60)

as the url contains `&fit=crop` 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MACOS
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 73

**Additional context**

**Comment by minecrawler** [comment]
Is this for the blog header? I guess they want uniform header dimensions, which I am all for, too, tbh.

**Comment by fazlerocks** [comment]
1.95 is the standard width x height ratio on all social networks. Hence, your image width and height should be 800px/420px or 1600px/840px. You have to maintain this ratio and fix.

**Comment by daveismyname** [comment]
yes I've replaced an image with the exact dimensions of 800 x 420 and it's not being cropped now.
