### ISSUE TITLE
Save posts

### ISSUE THREAD

**Issue by M-Saeb** [Hashnode/user-feedback#142]
I  can't tell you the number of times I've come across blogs that I'm really interested in but I don't have the time to read it at the moment. And then when I come back to it several hours later I have to keep scrolling down until I find it. It's a painful process that can be easily skipped just by adding new a "save post" feature.

**Comment by theevilhead** [comment]
Hey @M-Saeb,
We already have the bookmarking feature. Check out the top-right corner of every post.

<img width="859" alt="Screen Shot 2019-11-13 at 3 12 13 PM" src="https://user-images.githubusercontent.com/12823517/68751837-4982f880-0628-11ea-8091-478174989aad.png">

**You can check your bookmarked posts here 👇**

<img width="1228" alt="Screen Shot 2019-11-13 at 3 13 39 PM" src="https://user-images.githubusercontent.com/12823517/68751797-3b34dc80-0628-11ea-8a46-5f819986c15e.png">
https://hashnode.com/bookmarks

Thank you for your time :)
