### ISSUE TITLE
Like bar unreadably overlays DevBlog articles

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#145]
**Describe the bug**
The like buttons do not have a background and hover over the article, which looks broken.

**To Reproduce**
1. Go to https://bolajiayodeji.com/writing-good-commit-messages-a-practical-guide-ck3izs56t00sed0s11z515m1j
2. Scroll down

**Expected behavior**
Should have a non-transparent background

**Screenshots**
![image](https://user-images.githubusercontent.com/1130708/69869323-ceb71000-12ac-11ea-86b8-86d620b09bbc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10_64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 70.0.1 (64-bit)

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for raising this issue.
I can't seem to reproduce this error on my end, are you still experiencing this?

**Comment by minecrawler** [comment]
Hi @BolajiAyodeji , yes, I am still experienceing the issue, however I noticed that you have to resize the window in order to trigger the problem (reduce the width). That's something I regularly do, because I shuffle my windows around a lot during the day (maybe because I am lacking space? More monitors are always the solution, but I don't know where to put them haha). Anyway, after a reload the breakpoint properly triggers and the layout looks good. Maybe this is a problem with the components only reading their width once, but not hooking the window-resize? IIRC, that's a common problem and why libraries like ElementQueries exist.

**Comment by BolajiAyodeji** [comment]
Thank you @minecrawler.

I'll relate this bug to my team and get back to you.

**Comment by fazlerocks** [comment]
@minecrawler,

That happens on resizing the window. We'll fix it soon. Thanks for reporting.

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, this is fixed now.
