### ISSUE TITLE
Header bar enhancement

### ISSUE THREAD

**Issue by iamshadmirza** [Hashnode/user-feedback#15]
**Header bar in Home Screen**

Header bar can be improved. On scrolling up, it should reappear to navigate to different places. 

There should be something to reach at the top after scrolling too many articles.

**Comment by fazlerocks** [comment]
Hi @iamshadmirza, Thanks for the suggestion. Sounds useful to me. We will keep you posted on its status.

**Comment by BolajiAyodeji** [comment]
Hi @iamshadmirza, thanks for this feedback.

This is fixed now.
