### ISSUE TITLE
Stats on my articles

### ISSUE THREAD

**Issue by polilluminato** [Hashnode/user-feedback#151]
I'd like to suggest some sort of Analytics on post in this way you can track how many: total views, views/month, views/read/likes has an article. 
In the first iteration could be enough standalone stats, not filter or other fancy features.
Thee are some examples from Medium:

<img width="1025" alt="History graph" src="https://user-images.githubusercontent.com/202140/72502743-51366780-383a-11ea-8e97-8cfd544186d7.png">

<img width="1046" alt="Article stats" src="https://user-images.githubusercontent.com/202140/72502770-5f848380-383a-11ea-84bd-c22c7e96b743.png">

**Comment by BolajiAyodeji** [comment]
Hi @polilluminato, thanks for this feedback.

We're working on a similar feature already, we'll keep you updated.

**Comment by thamaraiselvam** [comment]
It is indeed a great feature to have. +1

**Comment by polilluminato** [comment]
As I said in this issue #141 I recently discovered that we can set a Google Analytics Tracking ID, so maybe this solve my issue to have stats on my articles.

I think it's still useful to have mini statistics on the platform so that you don't have to set up a Google account in order to extract them.
