### ISSUE TITLE
Sizing issues with mobile devices

### ISSUE THREAD

**Issue by hawkeye2013** [Hashnode/user-feedback#157]
**Describe the bug**
When using my dev blog website on a mobile phone I found three different issues with the layout of the page.  They are listed below:

1) Sign in button text is too large or the button is not wide enough.  This causes the break between Sign and in and causes the header to be disproportionally high when compared to everything else in that same line.

2) Light/Dark mode button turns into an oval when on mobile (See photo below).

3) When trying to navigate to another page, and the pages overflow, tapping the page name only causes the scroll bar to open, covering half the page names.  This means that you have to try and tap the top portion of the link, which is almost impossible.  It seems that a hamburger menu in the top left corner would reduce the need for the overflow-x scroll action on the page list.

**To Reproduce**
1. Go to [EFFEXX](https://effexx.io) on mobile, not logged in

**Expected behavior**
1) I expect the Sign In button to appear on the same line, with the smaller font as it does on the desktop version.

2) I expect the Light / Dark mode button to render as a circle, not an oval.

3) I expect to be able to navigate to other pages by clicking on the link.

**Screenshots**
![IMG_1150](https://user-images.githubusercontent.com/14302456/74115879-198fb680-4b7f-11ea-88e5-6d4c9fc93ad6.jpg)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: 13.3.1
 - Browser: Chrome
 - Version 79.0.3945.73

**Comment by BolajiAyodeji** [comment]
Hi @hawkeye2013, 

Thanks for reporting this, we would look into this and get it fixed ASAP.

**Comment by fazlerocks** [comment]
Hey @hawkeye2013, thanks for reporting these issues. We have recently deployed a design refresh to Hashnode and all the Devblog. Hence, this issue is redundant now. Closing it.
