### ISSUE TITLE
Cannot scroll changelog pop-over on mobile

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#16]
**Describe the bug**

On mobile, long changelog entries cannot be viewed in full

**To Reproduce**
1. Go to Hashnode
2. Click on changelog
3. Select an entry

**Expected behavior**

Pop-over can be scrolled

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553091582652/dfTMxrmMg.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] ZTE Axon 7
 - OS: [e.g. iOS8.1] RR Android 8.1
 - Browser [e.g. stock browser, safari] chrome

**Additional context**

**Comment by fazlerocks** [comment]
Thanks for reporting this. It has been fixed.
