### ISSUE TITLE
Project critisizm and suggestion

### ISSUE THREAD

**Issue by opeodedeyi** [Hashnode/user-feedback#162]
**Is your feature request related to a problem? Please describe.**
getting suggestion and improvement to a project I am building

**Describe the solution you'd like**
I would like a case where I can post a project I am working on, what I have done, the features I want to implement and the rest. And I can get constructive criticism about the project, get input from people and maybe links from people on how they solved similar issues. The people that are criticizing could be getting ideas about projects to build, it could even lead to collaborations and potential startups, e.t.c. 

**Describe alternatives you've considered**
I haven't tried any solutions about this

**Additional context**
NO.

**Comment by BolajiAyodeji** [comment]
HI @opeodedeyi,

Thanks for this amazing suggestion.
We already have the [Show Hashnode](https://hashnode.com/feed/showhashnode) channel that allows you to share something that you've made with the Hashnode community. Get traction to your project and receive feedback.

Kindly try this out and if you need more help, please ensure to reach out.
Cheers!
