### ISSUE TITLE
Support image caption in editor and viewer

### ISSUE THREAD

**Issue by bendtherules** [Hashnode/user-feedback#166]
**Name of the feature**
Support image caption in Hashnode editor

**Describe the solution you'd like**
Allow some way to add caption for embedded images. Either through 

1. some kind of markdown extension which allows that
2. atleast show alt text also as caption
3. bestcase, allow custom html in markdown (like it's supposed to work)

**Describe alternatives you've considered**
Atleast show alt text also as caption

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @bendtherules,

thanks for this amazing feedback.

This is something I personally will want to see too, we would work around this and hope to give you feedback soon. Do have a great day :smiley:

**Comment by fazlerocks** [comment]
Hi @bendtherules, adding caption to image is supported by default by markdown. Please follow the following syntax: 

```
![](path/of/image)*Enter Caption here*
```

**Comment by bendtherules** [comment]
@fazlerocks Ahh, nice. 
Actually, I tried that earlier but the only problem was that if the image was less in width (than blog width), then the text would wrap around the image.

Looks like images are block-scoped now, so it looks fine.
