### ISSUE TITLE
Changelog notification re-appears on every separate browser

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#17]
**Describe the bug**
I am logged into Hashnode on many computers, and sometimes several browsers. Whenever there is a new changelog notification, I have to read it on every single browser.

**To Reproduce**
1. Open Hashnode in several browsers
2. Publish Changelog
3. Refresh all browsers

**Expected behavior**
The notification should be uniform with the rest of the notifications. They should go away in all browsers after reading them once.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows, Linux
 - Browser [e.g. chrome, safari] FF, Chrome
 - Version [e.g. 22] evergreen

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] ZTE Axon 7
 - OS: [e.g. iOS8.1] RR Android 8.1
 - Browser [e.g. stock browser, safari] Chrome
 - Version [e.g. 22] evergreen

**Comment by fazlerocks** [comment]
Hi @minecrawler, we are using Headway for the changelog. They store notifications read status on the client side. There's no way to tie our user information with theirs. However, we will look into it and check if we can use their APIs and store the info on our servers.
