### ISSUE TITLE
Image Alt: Profile Image

### ISSUE THREAD

**Issue by AutoSponge** [Hashnode/user-feedback#175]
**Describe the bug**
Ensures `<img>` elements have alternate text or a role of none or presentation.

**To Reproduce**
Element location: `.user-photo[href$="\@sandeep"] > img`
Element source:
```
<img src="https://hashnode.imgix.net/res/hashnode/image/upload/v1546597615910/SyOxr3hbE.jpeg?w=320&amp;h=320&amp;fit=crop&amp;crop=faces&amp;auto=format&amp;q=60">
```

Fix options:
- Add `alt=""` to these images since their name appears in the card and remove the link
- Add `alt="<user name> profile"` to provide an accessible name to the link surrounding the image.

**Comment by fazlerocks** [comment]
Hey @AutoSponge, thanks for reporting this. We have deployed a fix.
