### ISSUE TITLE
#whoishiring section error

### ISSUE THREAD

**Issue by surajrathod** [Hashnode/user-feedback#176]
**Describe the bug**
#whoishiring causing the page to scroll left in the mobile view 

**To Reproduce**
1. Go to 'https://hashnode.com/feed/whoishiring'
3. Scroll down to '#whoishiring' content 
4. change the view to "MobileView"
5. Scroll left right

**Expected behavior**
there should not be scroll left and right when we change to mobile view

**Screenshots**
black box is the error and red box is the causing area
[](url)
![hashnodeerror](https://user-images.githubusercontent.com/12035730/77816338-05c8f100-70e8-11ea-8c68-d4d94efee940.png)

**Bug Fix**
Add 'flex-wrap' class to the red box area to resolve the bug or error

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, Firefox]
 - Version [e.g. 74.4]

**Smartphone (please complete the following information):**
 - Device: [Motorola Moto One Power]
 - OS: [Android]
 - Browser [Chrome]
 - Version [80]

**Additional context**

**Comment by fazlerocks** [comment]
Hey @surajrathod, thanks for reporting this bug. We have deployed a fix.
