### ISSUE TITLE
Elements w/ style class "follow-button" invisible

### ISSUE THREAD

**Issue by boghyon** [Hashnode/user-feedback#177]
## Describe the bug
Hashnode uses sometimes `.follow-button` CSS class on `<button>`s or `<href>` elements. E.g.:

* The <kbd>Update</kbd> button on https://hashnode.com/settings:
  ```html
  <button class="follow-button text-lg">Update</button>
  ```
* <kbd>Create an account</kbd> element on the front page
  ```html
  <a href="/signup" class="follow-button mb-2 text-lg px-4 py-2">Create an account</a>
  ```
* And more...

Adblockers, having millions of users, make those elements invisible (via `display: none`) due to _Fanboy's Annoyance_ / _Fanboy's Social_ filter list. Luckily, that list isn't enabled by default, but it's there. It's also possible that other filter lists in the future implement a similar rule.

## To Reproduce
1. Install _[uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)_
2. Navigate to its options: 
 chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#3p-filters.html
3. Enable _Fanboy's Annoyance_ or _Fanboy's Social_
4. Visit Hashnode's [front page](https://hashnode.com/) or [profile setting](https://hashnode.com/settings).

## Expected behavior
* Hashnode doesn't use the name `follow-button` for elements that do not semantically convey _following someone/thing_ like <kbd>Create an account</kbd> or <kbd>Update</kbd> buttons. E.g.:
  ```html
  <!-- Instead of class="follow-button ..." -->
  <button class="hn-update-button ...">Update</button>
  ```
* For legitimate <kbd>Follow</kbd> buttons such as in https://hashnode.com/members, the class name is prefixed with e.g. "hn-": `class="hn-follow-button"`.

## Additional context
I reported to the filter list maintainer that the `follow-button`-rule should be excluded in Hashnode.
But:

1.  There is no guarantee that the maintainer actually excludes Hashnode from the rule
2.  Future filter lists could implement a similar rule unknowingly that this might trigger false positives.

**Comment by fazlerocks** [comment]
Thanks for reporting this, we'll send a fix for this shortly.

**Comment by BolajiAyodeji** [comment]
Hi @boghyon, this issue is fixed now. Thank you once again :+1:
