### ISSUE TITLE
Followers Suggestion System

### ISSUE THREAD

**Issue by anikethsaha** [Hashnode/user-feedback#18]
**Is your feature request related to a problem? Please describe.**
It is not relating to a problem but keeping it will definitely help the new users as well as the existing one to reach to target content and users quickly which now is quite slow and not so efficient

**Describe the solution you'd like**
The following data can be used as parameters for computing suggestion 
- The skills or community tags ( of course )
- based on appreciations 
- Mutual connections or followers

**Describe alternatives you've considered**
Showing the users list whenever clicking on the follow button much like LinkedIn 

**Additional context**
N/A

**Comment by BolajiAyodeji** [comment]
Hi @anikethsaha, thanks for this feedback.

We would look into this.

**Comment by BolajiAyodeji** [comment]
Hi @anikethsaha, this is implemented already. Thanks a lot for your patience.
