### ISSUE TITLE
Sidebar Profile Section 

### ISSUE THREAD

**Issue by alexitaylor** [Hashnode/user-feedback#19]
**Describe the bug**
Unable to navigate to links (Posts, Comments, Appreciations, Followers, or Following) in the Sidebar Profile Section on my Profile Page instead get redirected to Profile Page.

**To Reproduce**
1. Navigate to User Profile Page
2. Scroll to the Sidebar Profile Section 
3. Attempt to click one of the links (Posts, Comments....)
4. Get redirected to profile page.

**Expected behavior**
If I click the Comments link it should redirect me to my Comments or if I click Followers link it should redirect me to my followers.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: Chrome
 - Version: 72.0.3626.121

**Comment by fazlerocks** [comment]
Hi @alexitaylor, It's working for us. Currently, the profile cover photo covers most of the real state above-the-fold. Are you scrolling down? 

We are working on a new profile design.

**Comment by alexitaylor** [comment]
Attached is a screenshot of the left side-bar on the profile page with the 5 highlighted items in red. As a user I expect if I was to click on Comments link it would redirect me to my Comments, but currently it just redirects me to my profile page.

![Screen Shot 2019-03-28 at 11 16 39 AM](https://user-images.githubusercontent.com/3086807/55182947-0254ff80-514c-11e9-9c26-99fdbdd6e656.png)

**Comment by alexitaylor** [comment]
Closing the issue as the new profile design does not include the side-bar section described above.
