### ISSUE TITLE
RSS not refreshing

### ISSUE THREAD

**Issue by pavelloz** [Hashnode/user-feedback#193]
It looks like RSS froze up for quite some time.

Example:
https://pavelloz.hashnode.dev/rss.xml - last post visible is from Nov 17
https://pavelloz.hashnode.dev/ - there are 2 posts after that, one from Nov 25, another from Nov 26

**Comment by panda-sandeep** [comment]
Hey it was probably cached. Have purged it. Please check again. :)

**Comment by pavelloz** [comment]
Wow, that was fast :D
Works great 👍 

Any way i can bust cache myself in the future?

**Comment by panda-sandeep** [comment]
@pavelloz Yes, from your blog dashboard -> purge cache from quick actions sidebar

**Comment by pavelloz** [comment]
Ouh! I've almost seen it! Thank you :)
