### ISSUE TITLE
Auto republishing from Medium blog via RSS

### ISSUE THREAD

**Issue by fazlerocks** [Hashnode/user-feedback#2]
Allowing users to republish content from Medium blog to their own blog automatically via RSS. This will also take care of the canonical meta tag.

**Comment by pankajpatel** [comment]
Why not from RSS Feeds, not just medium but any?

**Comment by fazlerocks** [comment]
We'll check with Medium's RSS and if everything works flawlessly, we'll open it up for any RSS. Practically speaking, it shouldn't be a problem. :)

**Comment by daveismyname** [comment]
that would be awesome!
