### ISSUE TITLE
OG images for dev blogs don't work

### ISSUE THREAD

**Issue by mmaksimovic** [Hashnode/user-feedback#20]
**Describe the bug**

When I go to SEO tab and upload an image I expect to see that image to get pulled by Twitter, Facebook and others.

![Screenshot_393](https://user-images.githubusercontent.com/17824181/54807866-dedb1200-4c7e-11e9-9e89-7b858b8b6bad.png)

However, this is what I get on Twitter

![Screenshot_394](https://user-images.githubusercontent.com/17824181/54807906-f6b29600-4c7e-11e9-97c9-893dba2fe533.png)

And on Facebook, another image gets pulled in and Facebook throws an error

![Screenshot_395](https://user-images.githubusercontent.com/17824181/54807977-2792cb00-4c7f-11e9-8550-b2371c4711c4.png)

**Expected behavior**
When I share the link to my dev blog on social media, I expect to see the image I uploaded just for that purpose

**Comment by fazlerocks** [comment]
Hi @mmaksimovic, This has been fixed. :)
