### ISSUE TITLE
Profile image does not update upon upload

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#21]
**Describe the bug**
When updating my profile picture, I do not see if the update was successful, because the pic in the dialog stays the same. I have to refresh to see the change

**To Reproduce**
1. Go to profile
2. Click on edit
3. Upload new pic

**Expected behavior**
The image changes, or I at least get a success message

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22]evergreen

**Comment by fazlerocks** [comment]
@minecrawler This will be fixed in the upgraded profiles.
