### ISSUE TITLE
GitHub icon has a bad contrast in dark theme

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#22]
**Describe the bug**
When using dark theme, the GitHub icon on the profile page is disappearing

**To Reproduce**
1. Go to my profile in dark mode

**Screenshots**
![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553464249434/LHspW0hZu.jpeg)

**Comment by fazlerocks** [comment]
@minecrawler We are upgrading profiles on Hashnode. This problem should be fixed in the new update.

**Comment by minecrawler** [comment]
Ok, I will wait for the new profile and create new profile-bugs once it's live. Don't hesitate to create a beta to let more people check for bugs early 😉
