### ISSUE TITLE
Reaction Footer Space Reduction

### ISSUE THREAD

**Issue by MeCode4Food** [Hashnode/user-feedback#24]
**Name of the feature**
Footer Reaction Size Reduction

**Describe the solution you'd like**
Limit the amount of reactions on the bottom of the viewport to just one row

**Describe alternatives you've considered**
Though probably could reduce the amount of reactions to reduce the clutter on the screen especially at the bottom of the page, but perhaps reactions is an avenue that hashnode is considering at the moment.

**Additional context**
Right now the footer takes up a lot of reading space on non mobile responsive viewports

**Comment by minecrawler** [comment]
I don't really think that is an issue on desktops, however I agree for mobile. Does a mobile user really need to see a detailed list of reactions? If a user wants to see a detailed list, they can use a desktop, but on mobile, as a user, I just want to select an appreciation or see the total count, if at all.

**Comment by fazlerocks** [comment]
@minecrawler the appreciation bar isn't fixed on the mobile screen. However, it does consume a lot of space on smaller desktops. We are trying to figure out a solution for this.

**Comment by MeCode4Food** [comment]
Yes, sorry for being unclear, but the appreciation bar does consume a lot of viewspace for smaller desktops. On mobile this isn't an issue as the appreciation bar is hidden for mobile viewports

**Comment by BolajiAyodeji** [comment]
Hi @MeCode4Food, thanks for reporting.

This is fixed now.
