### ISSUE TITLE
Scoped CSS Customizations

### ISSUE THREAD

**Issue by pankajpatel** [Hashnode/user-feedback#3]
It would be great to have possibility to add custom CSS.

It can be validated before being saved, so that it is made sure that it is not affecting anything very badly.

**Comment by BolajiAyodeji** [comment]
Hi @pankajpatel 
This is a premium feature that would be available soon.
For now, you can only change the appearance of your header like so:

![image](https://user-images.githubusercontent.com/30334776/61945241-68854e00-af97-11e9-9582-01bb76821262.png)
You'll be notified when we release this feature, for now, I'll be closing this issue.
