### ISSUE TITLE
As an author, I want clear domain setting instructions

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#30]
**Name of the feature**
In the domain setting on the blog, there is an explanation how to set up the domain. It contains an example with `maruru.example.com` as domain.

**Describe the solution you'd like**
The text should use the actual domain I submitted.

Instead of

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553725051300/Up0p46k_R.jpeg)

I'd prefer:

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553725165431/EwadOvvgJ.jpeg)

**Comment by sandeeppanda92** [comment]
Hey, @minecrawler I just deployed a fix for this. Here is how it looks now:

<img width="824" alt="Screenshot 2019-03-28 at 9 36 33 AM" src="https://user-images.githubusercontent.com/6363251/55129407-02013800-513d-11e9-900e-5cd85c70c005.png">

Closing this issue. Feel free to reopen if you think something is still wrong.
