### ISSUE TITLE
[Style] Bad contrast in dark mode side-bar footer section

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#32]
**Describe the bug**
The GitHub icon again... in the sidebar menu on the left in dark mode.

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553774805445/p36msuic-.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by fazlerocks** [comment]
It'll be fixed in the deployment. Thanks for reporting.
