### ISSUE TITLE
Team page incomplete

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#33]
**Describe the bug**
There is at least one new face missing from the team page

**To Reproduce**
1. Go to the [team site](https://hashnode.com/team)
2. Find Dunja....

**Additional context**
While I don't know who's on the team and who should be on the page, as a user, I have to wonder why she is missing from your team site, especially since she made an elaborate welcome post and introduced herself to the users...

**Comment by fazlerocks** [comment]
We'll update it, thanks for the reminder.
