### ISSUE TITLE
As an author, I want to delete unpublished drafts

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#34]
**Is your feature request related to a problem? Please describe.**
I have drafts, but I cannot delete them. One of them is even entirely empty, but still shows up...

**Describe the solution you'd like**
Add a button on the [draft overview page](https://hashnode.com/drafts) to delete a draft via REST call.

**Describe alternatives you've considered**
Add a button on the editor page

**Comment by sandeeppanda92** [comment]
The latest deployment fixes this issue. Thanks for reporting this. :)
