### ISSUE TITLE
[Style] Bad contrast for load-more button in dark mode

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#35]
**Describe the bug**
Illegible text

**To Reproduce**
1. Go to a story with many comments
2. Use the dark mode
3. Scroll down

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553851697183/QF5oy-vX2.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by fazlerocks** [comment]
Has been fixed. Should be live in the next deployment.
