### ISSUE TITLE
[Style] Follow tags tag overview

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#36]
**Name of the feature**
Follow Tags overview page

**Describe the solution you'd like**
The scrollbar for the tags does not look very pleasant

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1553852302022/pHI83-q3M.png)

There is so much space which could be used to make a grid layout with items and icons.

**Describe alternatives you've considered**
If it has to be a scrolled view, why not make it a carousel? Again, with bigger items and icons, so it looks aesthetically nice.

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hello @minecrawler, 
I want to belive this has been fixed, let me know if you have other issues with this.

Thank you for raising this.

**Comment by minecrawler** [comment]
@BolajiAyodeji Thank you for your response, however my suggestion has not been addressed, yet. Please let me know if this is a decision by the team, or if you just closed my issue (without checking) because of the age.

[Link to affected page](https://hashnode.com/tags), compare to screenshot above.

**Comment by fazlerocks** [comment]
Hi @minecrawler,

It is a team decision. We are coming up with a new explore page for tags and popular posts. Hence, this page won't be upgraded. :) 

Fazle
