### ISSUE TITLE
Unexpected behavior when middle-clicking a notification

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#40]
**Describe the bug**
When middle-clicking any anchor or link on a website, the default behavior is that the link is reference url is opened in the background in a new tab (or window). When middle-clicking notifications on Hashnode, the reference url is opened in the foreground in a new tab and the notification list is closed in the original context.

**To Reproduce**
1. Click on notification
2. Middle-click a notification

**Expected behavior**
The notification is opened in another tab in the background, the notification list stays open and marks the notification I clicked on as read.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
