### ISSUE TITLE
VItal editor functions cease to work

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#42]
**Describe the bug**
Sometimes, vital editor functions, like creating a newline by pressing `[ENTER]`, stop working. TO me, the occurence of the bug looks random, but it happens, and it only happens on Hashnode. I have to open another program or reload the page to get back the functionality.

**To Reproduce**
1. Write an answer to a post
2. ???
3. Press enter, no new line

**Expected behavior**
Text editor just works™

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

To add a break line, please add double space after the original line and hit ENTER.

**Comment by minecrawler** [comment]
I don't want to add a break line, I just want a new line, which is possible in any multi-line text field. This seems to not always work on Hashnode, though :/

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for adding some more context.

We'll look into this and I'll update you.

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, are you still experiencing this? I can't seem to reproduce this.
Apologies for the delayed response.

**Comment by minecrawler** [comment]
It's been a while since I last saw this problem, so I think it's ok to keep it closed, thank you!
