### ISSUE TITLE
Image Upload does not work

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#44]
**Describe the bug**
The image upload does not longer work

**To Reproduce**
1. Create a new question
2. Click on image upload and select an image

**Expected behavior**
Upload works

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by sandeeppanda92** [comment]
This was a temporary glitch. Has been resolved. :) Thanks for the report though. 👍
