### ISSUE TITLE
As a user, I want to differentiate between different post types easily

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#45]
**Name of the feature**
Post-Type-Badges

**Describe the solution you'd like**
At the moment, only questions have a bade, so for a story, I have to twist my head around it not being a question. Maybe it's simple for new users, who get to know Hashnode now as a more story-centered platform, however, for me, it's difficult to see the difference at once, and I have to think more than I should. That's why I would love to have badges for each type of post, which is QUESTION and STORY at the moment (let's leave out news for now, because they live in a different feed anyway). Ideally, the badges should use different colors, so that I can recognize stories and questions easily.

**Describe alternatives you've considered**
Use icons instead of text. Icons are a great way to guide users without adding a too heavy visual overhead.

**Comment by fazlerocks** [comment]
Hi @minecrawler, there are only two types of posts on the main feed: Question and Story. Not showing labels for stories was a strategic decision which we have taken. We think it's mostly about getting familiar with the new system.

**Comment by minecrawler** [comment]
@fazlerocks Thank you for your reply! Maybe I am just not familiar, yet. Since it's a decision you made, I will close this issue for now.
