### ISSUE TITLE
Back to top Button

### ISSUE THREAD

**Issue by Hansum** [Hashnode/user-feedback#47]
**Name of the feature**
A back to top button

**Describe the solution you'd like**
An arrow up button where you click it and scrolls up back to the top when you're scrolling down a long time.

**Describe alternatives you've considered**
A Sticky navbar where you can click the hashnode logo to bring back to the top

**Additional context**
nothing 👍

**Comment by BolajiAyodeji** [comment]
Hi @Hansum, thanks for reporting.

This is fixed now.
