### ISSUE TITLE
As an author, I want to dismiss the user-mention-dialog

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#48]
**Name of the feature**
User Mention Dialog

**Describe the solution you'd like**
I cannot dismiss the user list pop-over, and if I try to move the cursor using the arrow keys, I instead move around the user list. It's tedious and annoying. I want to dismiss the user mention dialog by pressing `[ESC]` or clicking somewhere else.

**Comment by theevilhead** [comment]
It has been fixed. Thank you @minecrawler for suggesting this.
