### ISSUE TITLE
When switching the editor-view, the user-mention-dialog does not disappear

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#49]
**Describe the bug**
When switching the editor-view (for example from WRITE to PREVIEW), the user-mention-dialog does not disappear

**To Reproduce**
1. Create a new story
2. Press `[@]`
3. Change the view to PREVIEW

**Expected behavior**
pop-over disappears

**Screenshots**
![](https://cdn.hashnode.com/res/hashnode/image/upload/v1554367773615/fPFob8sp5.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by theevilhead** [comment]
This one is fixed too :) @minecrawler. Thank you again
