### ISSUE TITLE
Adding labels

### ISSUE THREAD

**Issue by daveismyname** [Hashnode/user-feedback#5]
I don't see the option to add labels when raising an issue I should see

![](https://i.imgur.com/ctTXTku.png)

but instead see

![](https://i.imgur.com/EzbGKI7.png)

**Comment by fazlerocks** [comment]
Thanks for writing this. We just realized Github doesn't allow outside contributors to add labels. 🤦‍♀️We will be using Issue templating to resolve this.

**Comment by fazlerocks** [comment]
@daveismyname I have updated the readme to use issue templating. 🍺
