### ISSUE TITLE
Appreciation bar does not stop at the bottom of the article

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#50]
**Describe the bug**
The appreciation bar keeps at the bottom of the window and hovers over other content

**To Reproduce**
1. Go to a long article
2. Scroll down

**Expected behavior**
Appreciation bar stops at the bottom of the article, above other content (like comments)

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1554395856107/lyAjqC1GQ.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
