### ISSUE TITLE
Default avatar behind transparent images

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#51]
**Describe the bug**
When using transparency in the avatar, the default profile avatar can be seen through in the notification pop-over.

**Expected behavior**
Neutral background

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1554396081221/5tgf4M_bi.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by fazlerocks** [comment]
Hi @minecrawler, thanks for reporting. It has been fixed. Should be live in the next deployment.
