### ISSUE TITLE
Choice of Light/Dark mode isn't kept when login.

### ISSUE THREAD

**Issue by PG-kura** [Hashnode/user-feedback#52]
**Describe the bug**
When I log in, always in light mode.

**To Reproduce**
1. Click on 'toggle theme' at dropdown opened from top right. (Switch to dark mode)
2. Click on 'log out' at below of that.
3. Click on 'Sign in'
4. Click on 'GitHub' to auth.

**Expected behavior**
I'm in dark mode.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Safari
 - Version: 12.1 (14607.1.40.1.4)

**Comment by fazlerocks** [comment]
Hi @PG-kura, theme preferences are stored in the cookies. They are not stored in our databases. If you switch browser or log out, the theme would revert back to the default theme (light).

**Comment by PG-kura** [comment]
I see. Thank you!
