### ISSUE TITLE
Code Block (Bug) 

### ISSUE THREAD

**Issue by bridgetsarah** [Hashnode/user-feedback#53]
**Describe the bug**
In the text editor, I'm finding when I try to use the code button <> that if I need to put in two separate blocks of code that it doesn't always show up.  So for example was just writing a response to this code. 

Ideally wanted a split between the HTML and HTML + JavaScript.

So tried writing it desperately in two blocks, did not work. Then clicked preview page and only one block appeared which was the HTML block but nothing for the HTML button. So then decided to move the code from the bottom block into the HTML block, hit preview and then the second block showed up?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g.Linux Mint Tessa]
 - Browser [e.g. chrome]
 - Version [Version 73.0.3683.103 (Official Build) (64-bit)]

**Comment by fazlerocks** [comment]
Hi @bridgetsarah 

You need to insert a line break between two code blocks. 

````
```
Code Block 1
```

```
Code Block 2
```
````

Please let me know if that works for you. :)

**Comment by bridgetsarah** [comment]
Ahh okay, thanks for letting me know, I'll try this again :)
