### ISSUE TITLE
Provide facility to disable highlightjs 

### ISSUE THREAD

**Issue by lorefnon** [Hashnode/user-feedback#55]
**Name of the feature**
Syntax highlighting in blog posts

**Describe the solution you'd like**
Highlightjs syntax highlighting is sometimes weird esp when it auto detects syntax for languages that are not supported. 

I think in these scenarios it would be fine to just not have syntax highlighting.

**Describe alternatives you've considered**

- Setting syntax as text to disable highlighting (which didn't work) 
- Using something like github gists or carbon (works, but time consuming when you have many tiny snippets).
- Directly using `<pre>` html tag (which don't work).

**Additional context**

Examples:

Eg. GraphQL: 

![image](https://user-images.githubusercontent.com/1449492/56523287-eb47d880-6564-11e9-9452-c3f235636bc1.png)

Complex JSX usage in typescript:

![image](https://user-images.githubusercontent.com/1449492/56523363-0286c600-6565-11e9-81e9-a1786c6b8766.png)

Alternative solutions could include supporting directly pasting syntax highlighted content copied from vscode (Ctrl+shift+p > Copy with syntax highlighting) or simply pasting images captured through a snipping tool.

**Comment by lorefnon** [comment]
As a workaround, I wrote a [simple script](https://gist.github.com/lorefnon/dccc263ad821164b6d2abb9222f90601) which post-processes a markdown document and converts code blocks to syntax-highlighted images generated by carbon.now.sh.

It significantly increases the size of the html page, but otherwise has been working fairly well.

**Comment by theevilhead** [comment]
Thank you for your time @lorefnon. The issue has been fixed 🍻

**Comment by lorefnon** [comment]
@theevilhead  What is the solution ?

**Comment by minecrawler** [comment]
@lorefnon I guess using 

```
```undefined
```

since we can now define the language (see #56 )
