### ISSUE TITLE
As an author, I want to enforce the language used for syntax highlighting

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#56]
**Name of the feature**
Code highlighting

**Describe the solution you'd like**
I want to enforce the language used for highlighting my code snippet. The auto-detection is wrong in many cases, or tries to highlight an unsupported language. I'd prefer to write the language name after the back-ticks, like:

```
    ```javascript
    const a = 0;
    ```

    bla bla

    ```undefined
    Pseudo code, whatever
    ```
```

**Comment by theevilhead** [comment]
Thank you for your time @minecrawler. This issue has been fixed 🍻
