### ISSUE TITLE
Poll answer should be visible on profile page too

### ISSUE THREAD

**Issue by imkrunal** [Hashnode/user-feedback#57]
**Describe the bug**
If you vote in the poll it will be visible on the post page. but when you are viewing that post on your profile page or post list page you can't see what you have voted for you have to open the post to see that.

**To Reproduce**
1. Go to 'Any post with poll'
2. Then 'vote for anything'
3. Then check your profile page.

**Expected behavior**
Votes should be visible in the post list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 10
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 73.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @imkrunal, thanks for reporting.

This is fixed now.
