### ISSUE TITLE
Direct Question shows up in recent immediately

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#58]
**Describe the bug**
Direct Question shows up in recent immediately. 

**Expected behavior**
Afaik it should not until it was answered by the asked party.

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1556090816311/bazwdXDmZ.png)

**Comment by fazlerocks** [comment]
@minecrawler are you sure that's a direct question? Can you please share the link to the question?

**Comment by minecrawler** [comment]
@fazlerocks yes, I am sure, [here's the link](https://hashnode.com/post/hi-john-your-company-name-cjuuth67y000pb7s1bij7jh81)

**Comment by minecrawler** [comment]
[Here](https://hashnode.com/post/still-interested-cjvkvidj5006f49s1b5wgw3o2)'s one more
