### ISSUE TITLE
Blog widget not in sync

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#59]
**Describe the bug**
While I like the new blog widget, it seems it is not updated when changes happen to the stats displayed. I once had four drafts. I deleted all of them, and it still shows four drafts (even though some time passed already)

**To Reproduce**
1. Go to drafts and delete one
2. Widget does not update

**Expected behavior**
The blog widget shows 0 drafts.

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1556110075682/ZRl-c4c5u.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
