### ISSUE TITLE
Blog Single-Sign-On not working

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#61]
**Describe the bug**
When going to my blog, I am always logged out (even though I am logged into Hashnode). I just clicked on the Dashboard link on the Hashnode widget, and it actually took me to the dashboard, then changed sites to the front-page, telling me that I am not logged in.

**To Reproduce**
1. Click on Dashboard link in widget

**Expected behavior**

I expect single-sign-on. When I am logged into Hashnode, I should also be logged into my blog. And when I then go to the dashboard, I expect to land on the dashboard, and not the front-page. Logging in also does not redirect me back to the dashboard, but to the front-page.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
