### ISSUE TITLE
"What's Next" forgets I marked twitter as done

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#62]
**Describe the bug**
I marked twitter as done yesterday, however today, it's unchecked again.

**Expected behavior**
Checked items should remain checked

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by sandeeppanda92** [comment]
Hey Marco, Could you mark as done again and see if it persists? I want to know if it always forgets or only sometimes because of API failure.

**Comment by minecrawler** [comment]
@sandeeppanda92 I marked it again when I wrote this issue and just now had to login again, too. This time the item stayed ticked. I can keep an eye on it and check back in 24h, if you want.

**Comment by minecrawler** [comment]
Closing this since I cannot reproduce it anymore and no one else seems to have this problem.
