### ISSUE TITLE
Add hashtags when sharing to Twitter

### ISSUE THREAD

**Issue by EmilMoe** [Hashnode/user-feedback#63]
**Name of the feature**
Share to Twitter

**Describe the solution you'd like**
Add tags as hashtags to the shared message, after.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by minecrawler** [comment]
Maybe add a mapping to twitter tags, which can be edited by Community Managers in the Community settings

**Comment by EmilMoe** [comment]
> Maybe add a mapping to twitter tags, which can be edited by Community Managers in the Community settings

They could simply whitelist those that are included and lowercase them in the message.

**Comment by EmilMoe** [comment]
Still waiting

**Comment by BolajiAyodeji** [comment]
Hi @EmilMoe, this issue is implemented now. Thanks for your patience :).
