### ISSUE TITLE
[Style] Following-page in dark mode looks strange

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#65]
**Describe the bug**
Probably some styling missing, which makes the light mode look good, but displays a grey container in dark mode. When there are many followed people, the container does not too noticeable, however for few followers, it makes the page look like it's missing styling.

**To Reproduce**
1. Go to a following page ([for example this one](https://hashnode.com/@TaurusJi/following))

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1556609688268/bgkcrXkZd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] evergreen

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
