### ISSUE TITLE
Word "false" appended to widgets

### ISSUE THREAD

**Issue by CasperBraske** [Hashnode/user-feedback#66]
**Describe the bug**
The word "false" is appended to some  in "single-community-widget" elements.

**To Reproduce**
1. Go to your user profile
2. Click on [tags](https://hashnode.com/tags) on the left sidebar menu
3. Browse some of the topic tabs (_Programming Languages_, _Blockchain_, _JavaScript_, _Web Frameworks_) and you will see the word "**false**" appended to the description of some widgets as the image bellow

**Screenshots**
![image](https://user-images.githubusercontent.com/700448/57013693-242a2200-6be3-11e9-8da5-1c3781033633.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Firefox Dev
 - Version 67.0b14 (64-bit)

**Comment by theevilhead** [comment]
Thank you for your time @CasperBraske. This has been fixed :)
