### ISSUE TITLE
Pirated content on "A Tribute to Java"

### ISSUE THREAD

**Issue by elizarov** [Hashnode/user-feedback#68]
**Describe the bug**
I found pirated content in hashnode post and see no other way to report it:
https://hashnode.com/post/a-tribute-to-java-cjk51wlqo018rsfs2st4w8nrn
is pirated from:
https://medium.com/@elizarov/a-tribute-to-java-c184cd97db8f

**To Reproduce**
Compare contents of two links above.

**Expected behavior**
Pirated content to be taken down.

**Screenshots**

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**

**Comment by mmaksimovic** [comment]
Hey @elizarov

Thanks for reporting this! You can report any post by clicking on three dots below it and then click on the report button.

![Screenshot_445](https://user-images.githubusercontent.com/17824181/57209279-3d164700-6fd8-11e9-933a-f53892d14d49.png)

We have removed the post :)
