### ISSUE TITLE
Changelog is not appearing in correct position

### ISSUE THREAD

**Issue by Ipseeta** [Hashnode/user-feedback#69]
**Describe the bug**
Changelog popup is not properly visible 

**To Reproduce**
1. Go to 'Hashnode'
2. Click on 'changelog icon'
3. See error

**Expected behavior**
Changelog should appear in correct position.
**Screenshots**
![image](https://user-images.githubusercontent.com/20280934/57280934-8a251680-70c7-11e9-8970-61bf305c0752.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox
 - Version 66.0.3

**Smartphone (please complete the following information):**
For mobile nothing appears on clicking changelog
 - Device: iPhone7
 - OS: iOS 12.2
 - Browser: chrome

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @Ipseeta, thanks for reporting.

This is fixed now.
