### ISSUE TITLE
[Style] Big tech stack arrows

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#7]
**Describe the bug**
There is a CSS error with up/down buttons on my tech stack on my profile page

**To Reproduce**
1. Go to  [a profile with big tech stack](https://hashnode.com/@maruru) on a Desktop
2. Scroll to tech stack

**Expected behavior**
Should look nice and clean, according to the site's style

**Screenshots**

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1552660745620/pY9vTuOfp.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 66

**Additional context**

**Comment by theevilhead** [comment]
Hey @minecrawler,
The UI was updated. I will be closing this issue.
Thank you for reporting.
