### ISSUE TITLE
[UX] Middle-Click on user in followed/follower menu in profile acts unexpectedly

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#70]
**Describe the bug**
In the followed/follower menu in profile, when I middle-click a user, the page redirects to the user's profile.

**To Reproduce**
1. Go to follows-page on your profile
2. Click on any user with a middle-click
3. See error

**Expected behavior**
A new tab/window opens with the profile (browser default)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 67b

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for this feedback.

I don't seem to understand this feedback, on the click it is expected for it to redirect you to the user's profile in the same window. I'll be closing this, for now, please add some additional context and re-open.

**Comment by minecrawler** [comment]
No. I don't expect to be redirected on middle-click. I expect a new window/tab to open. I cannot re-open issues in this tracker, however I just tried it and this issue is fixed, now.
