### ISSUE TITLE
[Style] Blog icon in dark mode has bad contrast

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#72]
**Describe the bug**
Blog icon, as found on the profile page, has bad contrast in dark mode 

**To Reproduce**
1. Go to profile in dark mode

**Expected behavior**
Icon should be white, grey or blue

**Screenshots**
![](https://cdn.hashnode.com/res/hashnode/image/upload/v1557487786253/j0lk8iIJV.png)

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, thanks for reporting.

This is fixed now.
