### ISSUE TITLE
Error in draft when you writing story

### ISSUE THREAD

**Issue by malakarbiplab** [Hashnode/user-feedback#73]
Draft is not working, I writing one story from last 30 minutes and by mistakenly tab is reloaded. After that I did not found this story in my draft. Instead of this in my draft I found infinite story on sam time with no title and not body. And my this story have title and body also.

I think it is major issue. Because my 30 minutes now waste I need to start again. please look into this issue

**Comment by sandeeppanda92** [comment]
Hi Biplab! There was a temporary outage in one of our servers that creates drafts. Our UI should have shown an alert indicating that the draft creation failed. I must admit that this is a mistake on our end. We have fixed the draft creation process. To prevent this from happening in the future, we are going to show an alert on the UI in such events. We are truly sorry about this. :(

Sandeep

**Comment by Kedar-K** [comment]
@sandeeppanda92 I had the same problem. I was writing a blog and empty drafts got created automatically. There are around 208 empty drafts in my account right now :(

![Screenshot from 2019-05-13 00-04-46](https://user-images.githubusercontent.com/25702901/57586426-64f33680-7513-11e9-97cd-71ca258c9abb.png)

I hope that when this issue is fixed there is no need to delete all the drafts one by one and all those useless drafts are removed automatically.

**Comment by atapas** [comment]
> @sandeeppanda92 I had the same problem. I was writing a blog and empty drafts got created automatically. There are around 208 empty drafts in my account right now :(
> 
> ![Screenshot from 2019-05-13 00-04-46](https://user-images.githubusercontent.com/25702901/57586426-64f33680-7513-11e9-97cd-71ca258c9abb.png)
> 
> I hope that when this issue is fixed there is no need to delete all the drafts one by one and all those useless drafts are removed automatically.

Same here! Good to know that it is addressed now. 
I was thinking for an enhancement request to delete multiple drafts at once. I had delete 50+ drafts one by one. :)

**Comment by sandeeppanda92** [comment]
@atapas @Kedar-K Sorry about the trouble! This has been addressed now. 

Also, we are going to provide an option to delete multiple drafts with a single click so that you can get rid of all those drafts. Give us a day and we'll push this enhancement.
