### ISSUE TITLE
CodePen cannot be embedded

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#75]
**Describe the bug**
CodePen embeds are displayed as links instead of being embedded, using this markdown:

```
%[https://codepen.io/minecrawler/pen/ZNpLYx]
```

**To Reproduce**
1. Go to [this post](https://hashnode.com/post/text-positioning-cjvkvcyk2006d49s1cofnyr3m#cjvm5kimi0007tks1a6mbevxa)

**Expected behavior**
See CodePen embed

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 67.0b16

**Comment by theevilhead** [comment]
It's fixed along with many additional embeds. Thank you for your time @minecrawler
