### ISSUE TITLE
Can't create account... 

### ISSUE THREAD

**Issue by burtonator** [Hashnode/user-feedback#76]
I think your auth system is down. I can't create an account.

When I tried to create one before I got an unhandled exception about .split() 

... now when I try and go to through the login flow it just throws me back to / and I'm still not authenticated.

**Comment by sandeeppanda92** [comment]
It looks like you already have an account on Hashnode: https://hashnode.com/@burtonator

Could you try signing in via Google/GitHub?

**Comment by fazlerocks** [comment]
Hi @burtonator, please let us know if you were able to successfully sign in.
