### ISSUE TITLE
Cannot submit news

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#79]
**Describe the bug**
When I click on Submit, nothing happens for this link: https://bitbucket.org/blog/git-squash-commits-merging-bitbucket

**To Reproduce**
1. Go to Create News
2. Insert Link, add description and tags
3. Click submit

**Expected behavior**
News is submitted.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win64
 - Browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 67.0 (64-bit)

**Comment by sandeeppanda92** [comment]
Hi @minecrawler We have discontinued Link Sharing feature because of low community participation. We encourage everyone to share useful links, tips, and tricks through stories. You are probably seeing a cached version. If you reload the page, you will not find "Share News" link. :)

**Comment by minecrawler** [comment]
yeah, it's gone after clearing my cache. Bummer, though!
