### ISSUE TITLE
[Search] Dedicated Search Page

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#8]
**Name of the feature**
Dedicated Search Page

**Describe the solution you'd like**
As a user, when searching, I want to  see all search results in a clean and concise way. I want to get a search feed for each separate category (aka how Hashnode displayed searches a year ago), ideally with instant-search and jump-back when the search bar is emptied

**Describe alternatives you've considered**
Same as above, but with a filter which I can set for better results instead of fixed categories etc.

**Additional context**

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler ,
I actually don't understand what you mean here.
What do you mean by `I want to see all search results in a clean and concise way.`?

**Comment by minecrawler** [comment]
When I try to search a term on Hashnode, I get five mostly irrelevant results in a very short drop-down list, because they are "hot" or more current, plus a list of 10 or so users. That's not useful. I want a paginated overview. Often, I am looking for old posts, but cannot quite remember their titles, so the current search does not help me find anything. I usually use Google instead, just to get results. In this case, why even have search?

**Comment by BolajiAyodeji** [comment]
> When I try to search a term on Hashnode, I get five mostly irrelevant results in a very short drop-down list, because they are "hot" or more current, plus a list of 10 or so users. That's not useful. I want a paginated overview. Often, I am looking for old posts, but cannot quite remember their titles, so the current search does not help me find anything. I usually use Google instead, just to get results. In this case, why even have search?

My apologies for the late response.
Thank you for raising this issue, I'll relate this to my team and we'll get back to you.

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, this has been improved. Do let me know if you are still experiencing issues with this.

**Comment by minecrawler** [comment]
Hi @BolajiAyodeji I still only see the dropdown. Searching for keywords, I also get the feeling that it does not find all results. I get 15 results for the search-term "test", which seems like a little too few...
