### ISSUE TITLE
Better markdown support

### ISSUE THREAD

**Issue by tenuki** [Hashnode/user-feedback#80]
Some things that would be great to have in editor/articles:

1.  [TOC]  tag to include a Table of contents
2. support comments in markdown (i'm not sure if they are markdown-native but) many sites seems to support html comments inside markdown and prevents "commented" things to be rendered in output... like :  < ! - -  something which will not be rendered in output  - - >  (inserted extra spaces because if dont you wont see anything.. check:  )
3. other html markup enabled again in many markdown editors like: < s u p > 2 < / s u p >   (again spaces inserted to prevent it to be rendered to <sup>2</sup> )

**Comment by jameslei1024** [comment]
Besides, please add support to Latex formula in markdown.
It is essential to write some math formula when we write some technical blog.

**Comment by BolajiAyodeji** [comment]
Hi @tenuki, thanks for this feedback.

We support Markdown in comments and all places where you use the editor already. We don't support HTML tags for now and we would look into the *tag to include a Table of contents*.
