### ISSUE TITLE
Voting Results Briefly Appear Before Allowing You To Vote

### ISSUE THREAD

**Issue by mikebronner** [Hashnode/user-feedback#83]
**Describe the bug**
When opening a poll without having voted on it previously, the current standings are visible before the polling form is loaded. This could skew results for certain types of questions, where people might vote for the answer with the most voters, rather than voting their according to their own beliefs.

**To Reproduce**
1. Go to Q&A.
2. Click on any poll you haven't voted on yet.
3. Observe as the page loads, that the poll results are displayed before the voting form is loaded.

**Expected behavior**
The voting results should not load prior to having voted, and should not be displayable by CSS manipulation either.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser Safari 12.1.1

**Comment by BolajiAyodeji** [comment]
Hi @mikebronner, thanks for this feedback.

I can't seem to reproduce this error; the poll only shows the number of votes and duration left until I vote before it then displays the poll charts.

Are you still experiencing this?

**Comment by BolajiAyodeji** [comment]
Hi @mikebronner, any update on this?

**Comment by mikebronner** [comment]
Sorry, I am not using hash node anymore.

**Comment by BolajiAyodeji** [comment]
Hi @mikebronner, thanks for your response.
Do you mind telling me why you stopped using Hashnode? Did you experience any issue with our platform or it doesn't serve you anymore?

I'll be happier to help, best regards :)
