### ISSUE TITLE
Hamburger menu doesn't work

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#85]
**Describe the bug**
Clicking on the hamburger menu in the header doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:

1. Open hashnode site on mobile
2. Click on hamburger menu in header

**Screenshots**

![video-to-gif](https://user-images.githubusercontent.com/29014463/59000747-789b6f80-8829-11e9-834a-8520e6285fd6.gif)

**Comment by mittalyashu** [comment]
I have just opened the website on mobile and it seems like it working.

**Comment by fazlerocks** [comment]
Hi @mittalyashu, it might be due to slow internet. It seems to be working on our end.
