### ISSUE TITLE
Remove Algolia logo from search

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#86]
**Name of the feature**
You are using Algolia for the search bar and I guess with the free plan we only get 10000 data sets.

And with the current number of posts on the website, you must have already reached to higher number dataset and using a paid plan.

In that case, there is no need to show the Algolia logo anymore.

Since it required to show Algolia logo only if we are on free plan

![Screenshot_20190606-070701~2](https://user-images.githubusercontent.com/29014463/59000972-78e83a80-882a-11e9-9b90-9fc8414f5826.png)

**Comment by fazlerocks** [comment]
@mittalyashu We are on Algolia's community plan. It's a pro plan which is free forever. :)

**Comment by mittalyashu** [comment]
That's true it might be free, but it has certain limitations on the number of posts it can query.

![image](https://user-images.githubusercontent.com/29014463/59025737-74477480-8872-11e9-8bdd-356fcae04c92.png)

**Comment by sandeeppanda92** [comment]
@mittalyashu Algolia has been quite generous and has given us access to the PRO features at no cost. So, in a way, they are our sponsors and it's important for us to show our support. The above limitations don't apply to us.

<img width="504" alt="Screenshot 2019-06-06 at 5 12 51 PM" src="https://user-images.githubusercontent.com/6363251/59030452-a3fc7980-887e-11e9-8ec5-c9ab636d6cef.png">

**Comment by mittalyashu** [comment]
In that case, I take my words back 😆

That's great, Algolia has given you premium features for free.
