### ISSUE TITLE
Header too cluttered on mobile

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#87]
**Name of the feature**
In the current scenario the header looks too cluttered with all sorts of different icons few of them can be hidden only menu sidebar or profile drop-down.

Also the size is not `width: 100%` to the view port

![-video-to-gif (1)](https://user-images.githubusercontent.com/29014463/59001140-32471000-882b-11e9-88aa-9290733f8c8a.gif)

**Comment by fazlerocks** [comment]
Thanks for the feedback, @mittalyashu! We'll consider that.
