### ISSUE TITLE
Menu icon for changelog renders dropdown which is out of viewport

### ISSUE THREAD

**Issue by itsashis4u** [Hashnode/user-feedback#88]
**Describe the bug**
Menu icon dropdown is out of viewport

**To Reproduce**
1. Go to homepage
2. Click on Changelog icon (I believe)
4. Dropdown is out of viewport

**Screenshots**
<img width="1279" alt="hashnode" src="https://user-images.githubusercontent.com/4126695/59087571-a9130480-8922-11e9-8e57-9de66bad1f4f.png">

**Desktop (please complete the following information):**
 - OS: Macbook Pro 13 2015
 - Browser Chrome
 - Version 74.0.3729.169

**Comment by BolajiAyodeji** [comment]
Hi @itsashis4u, thanks for reporting.

Please check again as this is fixed now.
