### ISSUE TITLE
Hashnode devblog should trim the post at the previous dot of the exact length limit.

### ISSUE THREAD

**Issue by xuanquynh** [Hashnode/user-feedback#89]
**Name of the feature**
Please see the picture for more details!
![screenshot-xuanquynh hashnode dev-2019 06 08-19-56-23](https://user-images.githubusercontent.com/16967350/59156383-81f43880-8ac4-11e9-9b01-13400ea53a7f.png)

**Comment by BolajiAyodeji** [comment]
Hi @xuanquynh, thanks for this feedback.

Kindly make use of the **Issue: Feature Enhancement** template to help us better understand your feedback. I'll be closing this issue, for now, feel free to reopen once this is updated.
