### ISSUE TITLE
Unable to access my  blog dashboard

### ISSUE THREAD

**Issue by rvigneshw** [Hashnode/user-feedback#91]
While I click the setup blog button it takes me to the blog dashboard and suddenly entire page refreshes and I'm logged out and not able to sign in even if i do so it again repeats the same

**Comment by fazlerocks** [comment]
@aarvignesh which browser are you using? That should work.

**Comment by aarvignesh** [comment]
Using Brave browser(Version 0.65.120 Chromium: 75.0.3770.90 (Official Build) (64-bit))
As soon as it goes to /dashboard page it automatically refreshes and ask me to sign in even if do so the same thing repeats again

**Comment by aarvignesh** [comment]
Here are the screenshots

![image](https://user-images.githubusercontent.com/22572374/59579910-b1222f80-90ec-11e9-9824-8789d6c1398b.png)
![image](https://user-images.githubusercontent.com/22572374/59579932-c13a0f00-90ec-11e9-949a-825e4105c608.png)

**Comment by BolajiAyodeji** [comment]
Hi @rvigneshw, thanks for reporting.

Brave blocks third-party cookies by default which breaks our system. A fix is on the way. In the meantime, please turn your shield off in Brave for this blog. This is a temporary solution and we are coming up with a permanent fix in a couple of days.
