### ISSUE TITLE
As a user, I want to be able to go to my chat-partner's profile from the chat area

### ISSUE THREAD

**Issue by minecrawler** [Hashnode/user-feedback#93]
**Name of the feature**
Messaging system

**Describe the solution you'd like**
Click on name -> go to profile (just like everywhere else)

**Describe alternatives you've considered**
Add a button "See profile" if your third party lib is a hindrance to the implementation.

**Additional context**
Especially reporting a chat partner is really hard, and if they are already suspended, they do not show up in the search, which leaves me floating what happened and how to go on...

**Comment by fazlerocks** [comment]
@minecrawler The chat participants are displayed on the right-hand side on the desktop. 

<img width="1440" alt="Screenshot 2019-06-12 at 1 05 40 PM" src="https://user-images.githubusercontent.com/6068418/59332047-03d9a100-8d13-11e9-9a94-91e9515be9f8.png">

**Comment by fazlerocks** [comment]
We are working on showing this on smaller screens as well.

**Comment by minecrawler** [comment]
Ah, ok, I checked it on my mobile phone, which is probably why I missed the list. Would still be great to get the expected interaction on all avatars, if possible (?)

**Comment by fazlerocks** [comment]
Yes, we will make the avatar clickable. We are held back by the limitations of TalkJS.
