### ISSUE TITLE
Show somewhere if post is re-published

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#97]
**Name of the feature**

The post is getting re-published means it has been already published somewhere maybe by a same or different author in those cases it important that the original post should get the credit it deserves.

**Describe the solution you'd like**

Add a new block after the post ends, that this blog post was originally published by so and so.

Also, there can be a toggle option too if the user wants to make that block show on the specific blog or not.

**Comment by mittalyashu** [comment]
@fazlerocks, I guess the title is not very descriptive, can you update it.

**Comment by BolajiAyodeji** [comment]
Hi @mittalyashu, thanks for this feedback.

Right inside your editor, at the bottom-right corner, there is an option that allows you to enter the original URL of any re-published article so as to add as your canonical URL for SEO purposes.

![image](https://user-images.githubusercontent.com/30334776/72437394-ec7bfe00-37a2-11ea-82f6-cb9da29899eb.png)

Please read this as reference: https://townhall.hashnode.com/why-you-should-republish-your-devblog-posts-and-how-to-do-it-cjyzonun0004t4zs1r601f5ie
