### ISSUE TITLE
Tag image is not aligned on mobile

### ISSUE THREAD

**Issue by mittalyashu** [Hashnode/user-feedback#99]
**Name of the feature**

The image on the tag page is not aligned properly.

**Additional context**

![Screenshot_20190615-114424](https://user-images.githubusercontent.com/29014463/59549391-7304fe80-8f7a-11e9-815e-c2fd204d713f.png)

**Comment by BolajiAyodeji** [comment]
Hi @mittalyashu, thanks for reporting this.

This issue is fixed, please check again.
